# Tracking of A Circle In Free space

## Imports

In [2]:
%matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

## Importing Timestamps

In [3]:
t1 = pd.read_csv("t1.csv").to_numpy()
t2 = pd.read_csv("t2.csv").to_numpy()
t3 = pd.read_csv("t3.csv").to_numpy()
t4 = pd.read_csv("t4.csv").to_numpy()
t5 = pd.read_csv("t5.csv").to_numpy()

t1_points = np.nonzero(t1)
t2_points = np.nonzero(t2)
t3_points = np.nonzero(t3)
t4_points = np.nonzero(t4)
t5_points = np.nonzero(t5)

print(t1_points)
print(t2_points)
print(t3_points)
print(t4_points)
print(t5_points)

(array([1785, 1794, 1797, 1865, 1875, 1923, 1965]), array([1120,  859, 1146, 1110, 1199,  919,  986]))
(array([1361, 1377, 1381, 1426, 1517, 1526, 1672]), array([1120,  859, 1146, 1110, 1199,  919,  986]))
(array([ 839,  858,  863,  899, 1014, 1020, 1199]), array([1120,  859, 1146, 1110,  919, 1199,  986]))
(array([361, 377, 381, 426, 517, 526, 672]), array([1120,  859, 1146, 1110, 1199,  919,  986]))
(array([ 53,  62,  65, 133, 143, 191, 233]), array([1120,  859, 1146, 1110, 1199,  919,  986]))


In [61]:
def fivePointsToConic(points, f=1.0):

    x = points[:, 0]
    y= points[:, 1]

    from numpy.linalg import lstsq

    if max(x.shape) != 5:
        raise ValueError('Need = 5 points to solve for conic section')

    A = np.vstack([x**2, x * y, y**2, x, y]).T
    fullSolution = lstsq(A, f * np.ones(x.size))
    (a, b, c, d, e) = fullSolution[0]
    return (a, b, c, d, e, f)

In [5]:
def vals(points):
    from itertools import combinations
    comb = np.array(list(combinations((1, 2, 3, 4, 5, 6, 7), 5))).reshape(1, -1)
    val = np.zeros(2*(comb.size))
    for i in range(comb.size):
        val[2*i] = points[0][comb[0][i] - 1]
        val[2*i+1] = points[1][comb[0][i] - 1]
    val = val.reshape(-1, 5, 2)
    return val


In [49]:
from decimal import *

def majmin(a, b, c, d, e, f):
    is_ellipse = -1
    major = -1
    minor = -1
    try: 
        major = Decimal.sqrt((Decimal(2) * ((Decimal(a) * Decimal(e)**2 - Decimal(b) * Decimal(d) * Decimal(e) + Decimal(c) * Decimal(d)**2)/(Decimal(4) * Decimal(a) * Decimal(c) - Decimal(b)**2) - Decimal(f)))/(Decimal(a) + Decimal(c) - Decimal.sqrt((Decimal(a) - Decimal(c))**2 + Decimal(b)**2)))
    except:
        major = -1
    try:
        minor = Decimal.sqrt((Decimal(2) * ((Decimal(a) * Decimal(e)**2 - Decimal(b) * Decimal(d) * Decimal(e) + Decimal(c) * Decimal(d)**2)/(Decimal(4) * Decimal(a) * Decimal(c) - Decimal(b)**2) - Decimal(f)))/(Decimal(a) + Decimal(c) + Decimal.sqrt((Decimal(a) - Decimal(c))**2 + Decimal(b)**2)))
    except:
        major = -1
    if  b**2 - 4.0*a*c < 0 :
        is_ellipse = 1
    return(major, minor, is_ellipse)


In [47]:
def ellipse(t_points):
    NO_OF_COMBO = 21
    points = vals(t_points)
    eqns = np.zeros(0)
    for i in range(NO_OF_COMBO):
        (a, b, c, d, e, f) = (fivePointsToConic(points[0]))
        eqns = np.append(eqns, majmin(a, b, c, d, e, f))
    eqns = eqns.reshape( -1, 3)
    return eqns

In [62]:
ellipse(t1_points)

/tmp/ipykernel_12447/2551786532.py:12: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  fullSolution = lstsq(A, f * np.ones(x.size))


array([[Decimal('2007.808891663078431573417108'),
        Decimal('12410.31773367018851297101464'), 1],
       [Decimal('2007.808891663078431573417108'),
        Decimal('12410.31773367018851297101464'), 1],
       [Decimal('2007.808891663078431573417108'),
        Decimal('12410.31773367018851297101464'), 1],
       [Decimal('2007.808891663078431573417108'),
        Decimal('12410.31773367018851297101464'), 1],
       [Decimal('2007.808891663078431573417108'),
        Decimal('12410.31773367018851297101464'), 1],
       [Decimal('2007.808891663078431573417108'),
        Decimal('12410.31773367018851297101464'), 1],
       [Decimal('2007.808891663078431573417108'),
        Decimal('12410.31773367018851297101464'), 1],
       [Decimal('2007.808891663078431573417108'),
        Decimal('12410.31773367018851297101464'), 1],
       [Decimal('2007.808891663078431573417108'),
        Decimal('12410.31773367018851297101464'), 1],
       [Decimal('2007.808891663078431573417108'),
        Decima